/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CompanyStatus = IDL.Variant({
  'complete' : IDL.Null,
  'draft' : IDL.Null,
});
export const Company = IDL.Record({
  'id' : IDL.Nat,
  'status' : CompanyStatus,
  'name' : IDL.Text,
  'totalCapital' : IDL.Float64,
  'numShareholders' : IDL.Nat,
});
export const Shareholder = IDL.Record({
  'id' : IDL.Nat,
  'nationality' : IDL.Text,
  'lastName' : IDL.Text,
  'companyId' : IDL.Nat,
  'firstName' : IDL.Text,
});
export const CompanyWithShareholders = IDL.Record({
  'company' : Company,
  'shareholders' : IDL.Vec(Shareholder),
});
export const ShareholderInput = IDL.Record({
  'nationality' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  'createCompany' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [IDL.Nat], []),
  'deleteCompany' : IDL.Func([IDL.Nat], [], []),
  'getCompanies' : IDL.Func([], [IDL.Vec(CompanyWithShareholders)], ['query']),
  'getCompany' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CompanyWithShareholders)],
      ['query'],
    ),
  'updateCompanyShareholders' : IDL.Func(
      [IDL.Nat, IDL.Vec(ShareholderInput)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CompanyStatus = IDL.Variant({
    'complete' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Company = IDL.Record({
    'id' : IDL.Nat,
    'status' : CompanyStatus,
    'name' : IDL.Text,
    'totalCapital' : IDL.Float64,
    'numShareholders' : IDL.Nat,
  });
  const Shareholder = IDL.Record({
    'id' : IDL.Nat,
    'nationality' : IDL.Text,
    'lastName' : IDL.Text,
    'companyId' : IDL.Nat,
    'firstName' : IDL.Text,
  });
  const CompanyWithShareholders = IDL.Record({
    'company' : Company,
    'shareholders' : IDL.Vec(Shareholder),
  });
  const ShareholderInput = IDL.Record({
    'nationality' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    'createCompany' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [IDL.Nat], []),
    'deleteCompany' : IDL.Func([IDL.Nat], [], []),
    'getCompanies' : IDL.Func(
        [],
        [IDL.Vec(CompanyWithShareholders)],
        ['query'],
      ),
    'getCompany' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CompanyWithShareholders)],
        ['query'],
      ),
    'updateCompanyShareholders' : IDL.Func(
        [IDL.Nat, IDL.Vec(ShareholderInput)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };