/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Company {
  'id' : bigint,
  'status' : CompanyStatus,
  'name' : string,
  'totalCapital' : number,
  'numShareholders' : bigint,
}
export type CompanyStatus = { 'complete' : null } |
  { 'draft' : null };
export interface CompanyWithShareholders {
  'company' : Company,
  'shareholders' : Array<Shareholder>,
}
export interface Shareholder {
  'id' : bigint,
  'nationality' : string,
  'lastName' : string,
  'companyId' : bigint,
  'firstName' : string,
}
export interface ShareholderInput {
  'nationality' : string,
  'lastName' : string,
  'firstName' : string,
}
export interface _SERVICE {
  'createCompany' : ActorMethod<[string, bigint, number], bigint>,
  'deleteCompany' : ActorMethod<[bigint], undefined>,
  'getCompanies' : ActorMethod<[], Array<CompanyWithShareholders>>,
  'getCompany' : ActorMethod<[bigint], [] | [CompanyWithShareholders]>,
  'updateCompanyShareholders' : ActorMethod<
    [bigint, Array<ShareholderInput>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];